name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            # 1. Oprim absolut tot ce rulează vechi pentru a elibera portul 80
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true
            sudo docker system prune -f
            
            # 2. Curățăm folderul și aducem codul nou
            sudo rm -rf ~/app
            mkdir -p ~/app && cd ~/app
            git clone https://github.com/${{ github.repository }}.git .
            
            # 3. Ne asigurăm că avem docker-compose instalat
            sudo apt update && sudo apt install docker-compose -y
            
            # 4. Pornim noua structură (App + Prometheus + Grafana)
            sudo docker-compose up -d --build
