name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/app && cd ~/app
            sudo rm -rf * .git .github
            git clone https://github.com/${{ github.repository }}.git .
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker build -t my-app -f Dockerfile .
            sudo docker run -d --name my-app -p 80:3000 my-app
